export const BASIC_LOGIN = 'BASIC_LOGIN'
export const BASIC_LOGIN_ERROR = 'BASIC_LOGIN_ERROR'

export const BASIC_REGISTER = 'BASIC_REGISTER'
export const BASIC_REGISTER_ERROR = 'BASIC_REGISTER_ERROR'
