export default [
    'id',
    'createdAt',
    'updatedAt',
    'name',
    'description',
    'fileName',
    'fileSize',
    'fileExt',
    'timesPlayed',
    'trackNumber',
    'isDownloadable',
    'isExplicit',
    'tags',
    'user',
]
